Make FTPClient precompileable
invenia/FTPClient.jl pull request #52
Opened 2018-01-30 17:50 UTC by kano31

closes #48

2018-01-30 23:40 UTC, iamed2 requested changes

2018-01-30 23:40 UTC, iamed2 commented on src/FTPClient.jl
> +const C_WRITE_FILE_CB = Ref{Ptr{Void}}(C_NULL)
Judging from the code below, apparently there's a `Ptr{Cvoid}` now so we should use that. TIL!

2018-01-31 16:05 UTC, omus approved these changes
👍

2018-01-31 17:09 UTC, iamed2 approved these changes

2018-01-31 17:10 UTC, merged